### ISSUE TITLE
Decide on who does what.

### ISSUE THREAD

**Issue by xt0fer** [ZCW-Data2-2/CircusCircus#1]
Features to Add

comments on each post (many comments to one post)
like/dislike/heart/etc emojis on posts
direct messages from one user to another
insert pix links and/or video links
a nice style based on Bootstrap
a logo on every page
copyright, about etc on footer of each page
user settings
public/private posts
public posts can be seen by people not logged in
private posts can only be seen by users logged in
posts can be plain text or markdown

**Comment by croethel** [comment]
comments on each post (many comments to one post) - Tom
like/dislike/heart/etc emojis on posts - Tom
direct messages from one user to another - Keerthi
insert pix links and/or video links - Christine
a nice style based on Bootstrap - Efe
  -  a logo on every page
   - copyright, about etc on footer of each page
user settings - Drake
public/private posts - Creasen
   - public posts can be seen by people not logged in 
   - private posts can only be seen by users logged in
posts can be plain text or markdown -  Christine
